version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecoride
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./ecoride-server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ecoride
      - MONGODB_URI=mongodb://mongodb:27017/ecoride
      - JWT_SECRET=secret-token-ecoride-app
    volumes:
      - ./ecoride-server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./ecoride-client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./ecoride-client:/app
      - /app/node_modules

volumes:
  postgres_data:
  mongodb_data: